### ISSUE TITLE
Option to disable the "enabled" text via config

### ISSUE THREAD

**Issue by MrRomainzZ** [killer-kirito/afkAttack-fabric#1]
If someone doesn't like how it looks he can turn it off
![Screenshot_3](https://user-images.githubusercontent.com/47046463/104256838-f9ffbd00-54b6-11eb-853f-82d5111e167a.png)

**Comment by ThermalCube** [comment]
Sounds like a good enhancement. Will be added to the ToDo list

**Comment by ThermalCube** [comment]
@MrRomainzZ I uploaded a new release (version 1.1.0) which is still processing but should be available shortly
